use_frameworks!

target 'POPDropboxLib_Example' do
  pod 'POPDropboxLib', :path => '../'

  target 'POPDropboxLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
